name: Demo Github Action
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build 
      - name: Deploy
        run: echo "App Deployed"